### ISSUE TITLE
Firefly-RK3288 Linux Kernel

### ISSUE THREAD

**Issue by sghazagh** [rockchip-linux/kernel#14]
Sorry I am writing this question here as an issue.
I have a Firefly-RK3288 board. It's dual boot with android so recovery partition is used for linux kernel and at the moment official kernel 3.10.0 is compiled and loaded.

Can I use "kernel" in this repository to update only my Linux kernel on recovery partition of my Firefly-RK3288 board?
Please advise if boot partition (u-boot) needs to be updated as well.

Can you please give me the link to the best guide that I can use?
It seems that it is not normal kernel and dts file copy and I apparently have to make a kernel image with different format compatible with Firefly-rk3288 partitioning, correct?

Thanks for your assistance,

**Comment by wzyy2** [comment]
You can find guides in below link.
http://opensource.rock-chips.com/wiki_Main_Page

**Comment by sghazagh** [comment]
Thank you,
By the way, the part confuses me is "Building kernel" section!

Does Kernel Compilation, builds the kernel for Linux or for Android?
As I explained my board has dual boot which main OS is Android.
So it uses "Recovery" partition as boot partition for Linux. In fact the Linux Kernel needs to go to "Recovery" partition.
So the "Building kernel" section of the guide, creates the kernel for Linux or for Android?

**Comment by wzyy2** [comment]
There is no guide for booting kernel from old u-boot. I can show you a script which we use to ceate kernel image for old u-boot, but i'm not sure if it's suitable.
https://github.com/rockchip-linux/meta-rockchip/blob/morty/classes/rockchip-update-img.bbclass

I don't know how your dual boot is implemented and I'm afraid you have to study it by yourself.

**Comment by sghazagh** [comment]
Thanks wzyy2 for your help.
I actually started to create a SD image from scratch by creating kernel, u-boot and linaro-rootfs.

So far so good.
I have created the system image and trying to write it to SD.
It takes long time and still has not finished writing to SD. Not sure if it's right or wrong.
(it' just show **PARTITIONS OFFSET: 0 sectors.** for a long time and stuck in there but my HDD flashing slowly!!! I will wait to see what will happen...)

If that works, I stick to this repository for all Linux rootfs needs for my Firefly.

I do suggest to make a wiki a little bit more clear at the level explaining about SD images and making the SD image.

I will let you know the result if it works fine.

Let forget about the dual boot as I believe it will be more hassle while I can make a working board just with Linux....

will let you  know the result and will ask if I need any question.

I do appreciate your help...

**Comment by sghazagh** [comment]
No mate,
ubfortunatly the SD image does  not boot the Firefly.

Do I need to load u-boot or something else in device itself first?

Mine starts reading SD but cannot find the Partition tags.
Apparently it still looking for my old partition from partition table from eMMC and not SD itself?

Any advise?

**Comment by wzyy2** [comment]
erase emmc

**Comment by sghazagh** [comment]
All eMMC or only boot, kernel, u-boot? What about bootloader? how the board boots then?

What command do you use?
I only know "rkflashkit erase" which only erase partitions!

Should I use "rkdeveloptool EF" to erase whole eMMC? Does the board then boot from SD?

**Comment by wzyy2** [comment]
only loader1
You can use `rkdeveloptool wl 64(loader1 offset) dirty_content` to erase it

**Comment by sghazagh** [comment]
Jacob,
In official Firefly-rk3288 firmware, there is no loader1 partition.
The partition system named differently.
For example it has boot, misc, kernel, recovery...
Let me listthe partition file for your better understanding:

```
#Created By Firefly RK3288 'Parameter' File Generator 3.00
#ELAR Systems (http://www.elar-systems.com)
#Written By: Saeid Ghazagh (June 2016)
###########################################################
FIRMWARE_VER:4.4.2
MACHINE_MODEL: rk30sdk
MACHINE_ID:007
MANUFACTURER: RK30SDK
MAGIC: 0x5041524B
ATAG: 0x60000800
MACHINE: 3066
CHECK_MASK: 0x80
PWR_HLD: 0,0,A,0,1
#KERNEL_IMG: 0x62008000
#FDT_NAME: rk-kernel.dtb
#RECOVER_KEY: 1,1,0,20,0
CMDLINE:console=tty0 console=ttyS2 earlyprink androidboot.hardware=rk30board androidboot.console=ttyS2 board.ap_has_alsa=0 root=/dev/block/mtd/by-name/linuxroot rw rootfstype=ext4 init=/sbin/init initrd=0x62000000,0x00800000 mtdparts=rk29xxnand:0x00002000@0x00002000(uboot),0x00002000@0x00004000(misc),0x00008000@0x00006000(resource),0x00008000@0x0000E000(kernel),0x00010000@0x00016000(boot),0x00010000@0x00026000(recovery),0x0001A000@0x00036000(backup),0x00040000@0x00050000(cache),0x00002000@0x00090000(kpanic),0x00180000@0x00092000(system),0x00002000@0x00212000(metadata),0x00200000@0x00214000(userdata),0x00620000@0x00414000(linuxroot),-@0x00A34000(user)
```

So my question is that, how the boeard canuse SD with new partitioning as explaind in this repository?
Should I wipe whole eMMC and reload the system.img to eMMC first?
If not, what is the best approach to leave eMMC as what it is and just use SD to boot the Firefly with SD partitioning text file?

**Comment by wzyy2** [comment]
Ok.... Forget those boot things, it will confuse you..

**You should look at firefly wiki for how to boot into sdcard . I think they must have provided guides or tools to help.**

**Comment by sghazagh** [comment]
I can boot from SD to the Linux image I have created myself.
It actually uses same concept but I still use uboot, resource, kernel, misc and linuxrootfs partition.
So I know how it boots to SD. My Ubuntu 16.04 boots ok when I insert in SD.
The problem is that , I have no source for Kernel to update my version thats why I want to follow this repository and stick to this partitioning and setup.

Let me try by erasing the eMMC and load the loade1 to eMMC. I belive that is required to find the rootfs as it acts as first bootloader. That should then find the rootfs from SD and boot it.

Will let you know the result...

By the way, the I completely understand the Firefly-rk3288 official system. I haev written a Windows application to generate the partiotin.txt to load to partition table.
Have a look here, it's worth to try.
http://bbs.t-firefly.com/forum.php?mod=viewthread&tid=609&extra=page%3D1
[](http://bbs.t-firefly.com/forum.php?mod=viewthread&tid=609&extra=page%3D1)

I only need some guide to fit the Linux introduces in this repository into Firefly... Hope I can make it work by your help...

**Comment by wzyy2** [comment]
How do you boot from SD-Card without press maskrom button or earse emmc?
http://rockchip.wikidot.com/boot-sequence

Firefly board only support sd-card boot in mainline u-boot, so you don't need to try eMMC boot.

**Comment by sghazagh** [comment]
I give up mate...  even cannot erase the eMMc.
command "rkdeveloptool EF" does not work and says device do not support!

thanks for your support. I think it's better I stick to my current setup.

Hopefullt this repository works on my Asus Tinkerboard which is on the way to arrive....

**Comment by wzyy2** [comment]
Close it ....

I suggest you to google some keywords like  "firefly mainline u-boot" to boot mainline u-boot on your board at first .

**Comment by sghazagh** [comment]
I am using the mainline u-boot base on link bellow and all are ok to load my both android and linux.
Also I can load my own linux image from SD.

[http://wiki.t-firefly.com/index.php/Firefly-RK3288/Mainline_Kernel/en#U-Boot](http://wiki.t-firefly.com/index.php/Firefly-RK3288/Mainline_Kernel/en#U-Boot)

I don't know how I have to fit this repository system.img into eMMC or SD and how Firefly can boot them?

Hope anyone can help... I think it's better to keep it open as I as a user of Firefly-RK3288 couldn't be able to use this GIT Repository to boot my device!

**Comment by wzyy2** [comment]
Are you sure you are using mainline u-boot?

http://git.denx.de/?p=u-boot.git;a=summary
https://github.com/u-boot/u-boot/blob/master/doc/README.rockchip

**Comment by geekerlw** [comment]
you can change the kernel like firefly in this branch : https://github.com/T-Firefly/kernel_4.4/tree/firefly-rk3288  , just change some file like this commit : https://github.com/T-Firefly/kernel_4.4/commit/c2d8092ec7444cf11aa8ad6883bd4c7d3c5f74fd?diff=unified#diff-c085a0b86214742198c6dc024bb476efL379   , maybe you can get the kernel.img firefly use

**Comment by wzyy2** [comment]
> you can change the kernel like firefly in this branch : https://github.com/T-Firefly/kernel_4.4/tree/firefly-rk3288 , just change some file like this commit : T-Firefly/kernel_4.4@c2d8092?diff=unified#diff-c085a0b86214742198c6dc024bb476efL379 , maybe you can get the kernel.img firefly use


I think it's not enough to boot.
Kernel config also need be changed to use kernel.img.  e.g: CONFIG_ARM_APPENDED_DTB,  CONFIG_CMDLINE

**Comment by wzyy2** [comment]
> I give up mate... even cannot erase the eMMc.
command "rkdeveloptool EF" does not work and says device do not support!
thanks for your support. I think it's better I stick to my current setup.
Hopefullt this repository works on my Asus Tinkerboard which is on the way to arrive....

You miss a key word : **MASKROM mode**
That's why you are stick ...
**rkdeveloptool are used in maskrom mode.**

Please read blow link to know what is loader mode, what is maskrom mode, why it need enter maskrom mode, why it need erase emmc, how to make chip load u-boot from sd-card.
http://opensource.rock-chips.com/wiki_Rockusb
http://rockchip.wikidot.com/boot-sequence
http://opensource.rock-chips.com/wiki_Boot_option
http://wiki.t-firefly.com/index.php/Firefly-RK3288/Boot_mode/en
https://github.com/u-boot/u-boot/blob/master/doc/README.rockchip#L65


Sorry, I may provide too much extra and useless info and suggestions.. I prefer people to understand what they are doing instead of giving steps.

To boot into sd-card, you just need those steps:  1.insert sd-card  2. try enter maskrom 3. The board will boot into sd-card..

**Comment by sghazagh** [comment]
Ok all,
Finlay I got it working.
I just use MASKROM mode to be able to boot from SD.

I also had to adjust the root device. I set the root to partition 7 of SD but don't know why the extlinux.conf is set it to something else. It's not a big deal, I will find it...
Please let me know if you aware which extlinux populated at the time of making the system.img!

I also need to know how can I get it run from eMMC or how tell the eMMC boot to SD if SD is in place. It normally does that but not for this SD image!!!

Anyway,
thank you all for all your assistance.
I think I made a good progress...

**Comment by sghazagh** [comment]
Jacob,
Many thanks for documents links. I read all of them and now better understand this repository Linux and all it's components like u-boot,kernel...

Firefly official uses different partitioning and tools but here is straight forward too.
I needed to dig into all the scripts to see what is happening to understand them.

Very good view...
Thanks a bunch ;)

**Comment by sghazagh** [comment]
Jacob/All,
Yesterday I didn't know much about this repository and it's RK3288 images and partitions.

Today, I was able to load my own created Ubuntu 16.4.2 LTS from eMMC with kernel 4.4.55 from this repository Kernel source, plus able to boot from both eMMC and SD.(boots from SD if it presents otherwise loads from eMMC)

I would like to thank you all for providing the Documentation.
It helped a lot.

Thank you

For Firefly-RK3288 Users: The "build/mk-image.sh" image cannot load the system.img into eMMC due to Firefly optimized chip.
You have to use "upgrade_tool" to populate your bootloader/u-boot , kernel and rootfs.
