### ISSUE TITLE
RK3399 resets 5 minutes after cold boot and 2 minutes after warm boot

### ISSUE THREAD

**Issue by novag** [rockchip-linux/kernel#147]
Solved. Hardware problem.

**Comment by noloader** [comment]
@novag,

I can't answer the questions, but... I can say a [Tinkerboard running Debian 9.8](https://dlcdnets.asus.com/pub/ASUS/mb/Linux/Tinker_Board_S/20181023-tinker-board-linaro-stretch-alip-v2.0.8.img.zip) runs fine and does not spontaneously reboot.

**Comment by Caesar-github** [comment]
Not any useful information was provided, I don't know what i can do for you?
