### ISSUE TITLE
SPI: random data length/tx/rx for DMA SPI transfers (eg. size over 32 bytes) "CONFIG_SPI_ROCKCHIP"

### ISSUE THREAD

**Issue by mcerveny** [rockchip-linux/kernel#19]
SPI driver CONFIG_SPI_ROCKCHIP (drivers/spi/spi-rockchip.c) does not work for transfers over 32 bytes (switched to DMA transfers, [see rockchip_spi_can_dma()](https://github.com/rockchip-linux/kernel/blob/release-4.4/drivers/spi/spi-rockchip.c#L631)). Totally random length/rx/tx are send and received with rk3288 (TinkerBoard, TinkerOS 1.8). Checked with external protocol analyzer and testing code:
```
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>
#include <inttypes.h>
#include <linux/spi/spidev.h>
#include <linux/types.h>
#include <sys/ioctl.h>
#include <linux/ioctl.h>

// SZ <= 32 OK (PIO transfers), >32 radom length send, random data send (checked from logic analyzer), random data received (DMA transfers)
#define SZ 33

int main()
{
	int fd = open("/dev/spidev2.0", O_RDWR);

	uint8_t mode = SPI_MODE_3;
	ioctl(fd, SPI_IOC_WR_MODE, &mode);
	ioctl(fd, SPI_IOC_RD_MODE, &mode);

        struct spi_ioc_transfer xfer;
	memset(&xfer, 0, sizeof(xfer));

	uint8_t tx_buf[SZ] = "\03\0\0\0";  // "\03\0\0\0" read from SPI flash or "\237" Manufacturer and Device ID Read (len 7)
        uint8_t rx_buf[SZ];

	xfer.tx_buf = (unsigned long)&tx_buf;
	xfer.rx_buf = (unsigned long)&rx_buf;
	xfer.len = sizeof(rx_buf);
	xfer.speed_hz = 10000000;
	xfer.bits_per_word = 8;

	int status = ioctl(fd, SPI_IOC_MESSAGE(1), &xfer);

	printf("status %d\n", status);
	int i;
	for(i=0; i<sizeof(rx_buf); i++) printf("%02x ", rx_buf[i]);
	printf("\n");

	close(fd);

	return 0;
}
```

**Comment by wzyy2** [comment]
Could you revert this commit and test again?
https://github.com/rockchip-linux/kernel/commit/e0a1e9b7cded261847ac972311082724afb75cbd

**Comment by mcerveny** [comment]
Not resolved by revert (tested on https://github.com/TinkerBoard/debian_kernel). Even worse than previous state. Just noticed that kernel become corrupted after few runs (~3 with reverted patch, ~20-30 with patch) and all application are failing and kernel finally hangs (usually "**Internal error: Oops: 37 [#<nolink>1] SMP ARM**").

Can anyone describe differences to other "DW SPI" code in https://github.com/rockchip-linux/kernel/tree/release-4.4/drivers/spi (eg. spi-rockchip-* and spi-dw* by intel) ?

Simple workaround (disable DMA mode):
```
diff --git a/drivers/spi/spi-rockchip.c b/drivers/spi/spi-rockchip.c
index 9e86ec35c45..adb6dc5ca0a 100644
--- a/drivers/spi/spi-rockchip.c
+++ b/drivers/spi/spi-rockchip.c
@@ -632,9 +632,7 @@ static bool rockchip_spi_can_dma(struct spi_master *master,
 				 struct spi_device *spi,
 				 struct spi_transfer *xfer)
 {
-	struct rockchip_spi *rs = spi_master_get_devdata(master);
-
-	return (xfer->len > rs->fifo_len);
+	return false;
 }
 
 static int rockchip_spi_probe(struct platform_device *pdev)
-- 
```

**Comment by Tonymac32** [comment]
I believe this may also be an error on Rock64 at the present time:

https://forum.armbian.com/index.php?/topic/4583-rock64/&do=findComment&comment=34978

**Comment by wzyy2** [comment]
> I believe this may also be an error on Rock64 at the present time:
https://forum.armbian.com/index.php?/topic/4583-rock64/&do=findComment&comment=34978


It's fixed.

**Comment by mgilge** [comment]
Did you do the disable DMA workaround in the rockchip-linux or the tinkerboard-linux? What is the difference between the two anyway?

**Comment by mcerveny** [comment]
Workaround was tested rockchip-linux and should work with all forks. Tinkerboard linux was forked from rockchip-linux (probably branch "release-4.4-miniarm" sometimes last year). ASUS TinkerBoard team is ignoring any development in rockchip-linux (do not rebase or merge patches - compare with https://github.com/TinkerBoard/debian_kernel). TinkerBoard is dead for me (check [tinkerboard forum](https://tinkerboarding.co.uk/forum/thread-440-post-1386.html#pid1386)).
I did not find or test announced fix.

**Comment by mgilge** [comment]
Thanks for getting back to me. We just use the Tinkerboard as a server platform.
But we need the SPI in order to connect a status display (paper = PaPiRus).

Is there a possibility to exchange just the patched SPI-driver on our SD-card without recompiling the kernel?

**Comment by geneshuman** [comment]
I'm a bit confused.  Was this issue ever resolved?  I seem to be running into it as well, although maybe I'm just running an old kernel.
