### ISSUE TITLE
failed to open rockchip drm: No such file or directory

### ISSUE THREAD

**Issue by lefu999** [rockchip-linux/kernel#191]
CONFIG_DRM_ROCKCHIP=y 
modetest种drmOpen("rockchip", NULL) 直接报错

**Comment by rkchrome** [comment]
modetest -M rockchip xxx

**Comment by WangPeng888** [comment]
> modetest -M rockchip xxx

您好，我也遇到  failed to open DRM:No such file or directory 的问题。
已实现lcd驱动，有/dev/dri/card0设备。也使用modetest -M rockchip xxx测试了显示屏，是ok的。
运行qt程序的时候报错.   请问这个问题怎么解决啊？

[root@RV1126_RV1109:~]# ./qt_test
failed to open DRM:No such file or directory.
Rga built version:version:1.00
"pine" "pineapples"
failed to open DRM:No such file or directory.
failed to open DRM:No such file or directory.
failed to open DRM:No such file or directory.
failed to open DRM:No such file or directory.
