### ISSUE TITLE
rk3288 Firefly Kernel Modules

### ISSUE THREAD

**Issue by sghazagh** [rockchip-linux/kernel#22]
Hi,
I see that the kernel is not going to build in your build script.
I remembered from past that we use Android libhybris and mount it as /system to get access to modules!
Is it still the case?
If not, why we do not build kernel modules?
If we create them, does it work on Firefly board?

I do appreciate if you explain me in detail to understand how the modules work on Firefly with your Kernel!
Thanks

**Comment by wzyy2** [comment]
You should search the online guides....... There is no differences with this kernel.

The reason why this kernel didn't build kernel modules is that rockchip_linux_defconfig configure all modules as  built-in modules.
