### ISSUE TITLE
Where are mpp and gstreamer-rockchip?

### ISSUE THREAD

**Issue by chichivica** [rockchip-linux/kernel#229]
Hello guys!
Many thanks for your work.
I'm just wondering where are **mpp** and **gstreamer-rockchip** repos?

**Comment by grkblood13** [comment]
And ffmpeg! They removed a lot of stuff.

**Comment by gusarg81** [comment]
Yes, please this is very important... You need  to document these things man... is a Shame how Rockchip  handles all this stuff...

Please respond @eddiecailinux @Caesar-github @keveryang

**Comment by JeffyCN** [comment]
@chichivica ,

Those repos became private projects for license issue, and i've created a few mirrors for them:
https://github.com/JeffyCN/mirrors/branches/all
