### ISSUE TITLE
error compiling drivers/gpu/arm/midgard/mali_kbase_jd.c  

### ISSUE THREAD

**Issue by bschiett** [rockchip-linux/kernel#3]
using release-4.4 branch: 

make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -j4
... 
  CC      drivers/gpu/arm/midgard/mali_kbase_jd.o
drivers/gpu/arm/midgard/mali_kbase_jd.c: In function 'kbase_jd_umm_map':
drivers/gpu/arm/midgard/mali_kbase_jd.c:368:2: warning: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'size_t' [-Wformat=]
error, forbidden warning: mali_kbase_jd.c:368
...

**Comment by wzyy2** [comment]
caused by using more strict compiler rule..
casting it to 'long unsigned int ' explicitly.

**Comment by bschiett** [comment]
I fixed it by using %zu instead of %lu
