### ISSUE TITLE
RK3328 - ROCK64 Support

### ISSUE THREAD

**Issue by ChBirender** [rockchip-linux/kernel#38]
ROCK64 mentioned as device on http://opensource.rock-chips.com/wiki_RK3328
But no dedicated dts file in 
https://github.com/rockchip-linux/kernel/tree/release-4.4/arch/arm64/boot/dts/rockchip .
Please help by expert hands.

Please help to port
https://github.com/rock64-android/kernel/blob/thzy_develop/arch/arm64/boot/dts/rk3328-rock64.dts

**Comment by dalmatele** [comment]
one vote for this support.
I use rock64 to encode/decode video but not successful, gstreammer can not run,...

**Comment by wzyy2** [comment]
It's better if someone can send us a pull request.
; )

**Comment by ayufan** [comment]
You can always see all my changes to "be compatible with Rock64" here: https://github.com/rockchip-linux/kernel/compare/release-4.4...ayufan-rock64:release-4.4 :)

**Comment by dalmatele** [comment]
@ayufan: did it support encode/decode? Because I still have seen that it can not encoded/decoded in RK3328.

**Comment by ayufan** [comment]
What do you mean?

Decode / encode of vpu? Yes, it works for me

**Comment by dalmatele** [comment]
@ayufan Yes, by VPU. When I run mpp encode, in the kern.log file I've seen this:
mpp_dev_ioctl:545: unknown mpp ioctl cmd 40086c04
Then output is blank frame ( zero value when using hexdump to see).
What board you've used? I use rock64 with RK3328: https://www.pine64.org/?product=rock64-media-board-computer

**Comment by ChBirender** [comment]
I have requested the merge.
But Please read carefully I'm looking Android kernel v4.4 support for  Rock64.
https://github.com/rock64-android/kernel/blob/thzy_develop/arch/arm64/boot/dts/rk3328-rock64.dts
Thanks Ayufan.

Regards,
Birender Singh

**Comment by hizukiayaka** [comment]
We have had an internal version, please wait it release

**Comment by ChBirender** [comment]
Hello Dear hizukiayaka,

Should wait more ?

Regards.

**Comment by ChBirender** [comment]
Dear All,

In https://github.com/torvalds/linux/ source tree we have

https://github.com/torvalds/linux/blob/master/arch/arm64/boot/dts/rockchip/rk3328-rock64.dts file.

Can we refer to this after kernel version release v4.14/ ?

Release.

**Comment by wzyy2** [comment]
@yanghanxing It seems many people want a rock64 dts in relase-4.4 kernel, could you help sending it?

**Comment by ChBirender** [comment]
Congratulation to all,

Mr. Linus Torvalds, turn out to be faster.

4.14 having default support for ROCK64.

Regards.

**Comment by SinghBirender** [comment]
Dear Mr. Jacob Chen,

Is somebody working on Android Kernel 4.4 for RK3328 ?

Regards.

**Comment by ChBirender** [comment]
Dear Mr. @wzyy2 

Please help to propagate my query to Mr. Xinhuang Li in below commit.

https://github.com/rockchip-linux/kernel/commit/1934ca1c8e1e82eb9a12a417de358e338d75ddd4

Regards.

**Comment by ChBirender** [comment]
Dear Mr. @ayufan ,

Please help to provide kernel version 4.4 for Android.

Regards.

**Comment by ChBirender** [comment]
Dear Mr. @wzyy2 ,

But we started this issue to include ROCK64 board default support in offcial git directory provided by Rock-Chip.

Regards.

**Comment by ChBirender** [comment]
Dear Mr. @ayufan ,

Can you please check reply of Mr. Jacob Chen in 
https://github.com/rockchip-linux/kernel/commit/1934ca1c8e1e82eb9a12a417de358e338d75ddd4

Regards,
Birender Singh

**Comment by SinghBirender** [comment]
Dear Ms. @hizukiayaka ,

Thank you for the support.

But we are getting compilation failure with following command.
make ARCH=arm64 rockchip_defconfig
make -j8 ARCH=arm64 rk3328-rock64.img

scripts/kconfig/conf  --silentoldconfig Kconfig
Makefile:708: Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
  WRAP    arch/arm64/include/generated/asm/bug.h
  WRAP    arch/arm64/include/generated/asm/bugs.h
  WRAP    arch/arm64/include/generated/asm/checksum.h
  WRAP    arch/arm64/include/generated/asm/clkdev.h
  WRAP    arch/arm64/include/generated/asm/cputime.h
  WRAP    arch/arm64/include/generated/asm/current.h
  CHK     include/config/kernel.release
  WRAP    arch/arm64/include/generated/asm/div64.h
  WRAP    arch/arm64/include/generated/asm/delay.h
  WRAP    arch/arm64/include/generated/asm/dma.h
  WRAP    arch/arm64/include/generated/asm/dma-contiguous.h
  WRAP    arch/arm64/include/generated/asm/early_ioremap.h
  WRAP    arch/arm64/include/generated/asm/emergency-restart.h
  WRAP    arch/arm64/include/generated/asm/errno.h
  WRAP    arch/arm64/include/generated/asm/ftrace.h
  WRAP    arch/arm64/include/generated/asm/hw_irq.h
  WRAP    arch/arm64/include/generated/asm/ioctl.h
  WRAP    arch/arm64/include/generated/asm/ioctls.h
  WRAP    arch/arm64/include/generated/asm/ipcbuf.h
  WRAP    arch/arm64/include/generated/asm/irq_regs.h
  CHK     include/generated/uapi/linux/version.h
  WRAP    arch/arm64/include/generated/asm/kdebug.h
  WRAP    arch/arm64/include/generated/asm/kmap_types.h
  WRAP    arch/arm64/include/generated/asm/kvm_para.h
  WRAP    arch/arm64/include/generated/asm/local.h
  UPD     include/generated/uapi/linux/version.h
  WRAP    arch/arm64/include/generated/asm/local64.h
  WRAP    arch/arm64/include/generated/asm/mcs_spinlock.h
  WRAP    arch/arm64/include/generated/asm/mm-arch-hooks.h
  WRAP    arch/arm64/include/generated/asm/mman.h
  WRAP    arch/arm64/include/generated/asm/msgbuf.h
  WRAP    arch/arm64/include/generated/asm/mutex.h
  WRAP    arch/arm64/include/generated/asm/msi.h
  WRAP    arch/arm64/include/generated/asm/pci-bridge.h
  WRAP    arch/arm64/include/generated/asm/pci.h
  WRAP    arch/arm64/include/generated/asm/preempt.h
  WRAP    arch/arm64/include/generated/asm/resource.h
  WRAP    arch/arm64/include/generated/asm/rwsem.h
  UPD     include/config/kernel.release
  WRAP    arch/arm64/include/generated/asm/poll.h
  WRAP    arch/arm64/include/generated/asm/serial.h
  WRAP    arch/arm64/include/generated/asm/sembuf.h
  WRAP    arch/arm64/include/generated/asm/segment.h
  WRAP    arch/arm64/include/generated/asm/sizes.h
  WRAP    arch/arm64/include/generated/asm/socket.h
  WRAP    arch/arm64/include/generated/asm/simd.h
  WRAP    arch/arm64/include/generated/asm/sockios.h
  WRAP    arch/arm64/include/generated/asm/shmbuf.h
  WRAP    arch/arm64/include/generated/asm/swab.h
  WRAP    arch/arm64/include/generated/asm/switch_to.h
  WRAP    arch/arm64/include/generated/asm/termbits.h
  WRAP    arch/arm64/include/generated/asm/termios.h
  WRAP    arch/arm64/include/generated/asm/topology.h
  WRAP    arch/arm64/include/generated/asm/trace_clock.h
  WRAP    arch/arm64/include/generated/asm/unaligned.h
  WRAP    arch/arm64/include/generated/asm/types.h
  WRAP    arch/arm64/include/generated/asm/user.h
  WRAP    arch/arm64/include/generated/asm/xor.h
  WRAP    arch/arm64/include/generated/asm/vga.h
  CHK     include/generated/utsrelease.h
  WRAP    arch/arm64/include/generated/uapi/asm/kvm_para.h
  UPD     include/generated/utsrelease.h
  HOSTCC  scripts/dtc/dtc.o
  HOSTCC  scripts/genksyms/genksyms.o
  CC      scripts/mod/empty.o
  CC      kernel/bounds.s
gcc: error: unrecognized command line option ‘-mlittle-endian’
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
scripts/Makefile.build:266: recipe for target 'scripts/mod/empty.o' failed
make[2]: *** [scripts/mod/empty.o] Error 1
scripts/Makefile.build:411: recipe for target 'scripts/mod' failed
make[1]: *** [scripts/mod] Error 2
make[1]: *** Waiting for unfinished jobs....
  CHK     include/generated/timeconst.h
gcc: error: unrecognized command line option ‘-mlittle-endian’
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
Kbuild:19: recipe for target 'kernel/bounds.s' failed
make[1]: *** [kernel/bounds.s] Error 1
make[1]: *** Waiting for unfinished jobs....
  UPD     include/generated/timeconst.h
  HOSTCC  scripts/dtc/flattree.o
Makefile:1042: recipe for target 'prepare0' failed
make: *** [prepare0] Error 2
make: *** Waiting for unfinished jobs....
  SHIPPED scripts/genksyms/parse.tab.c
  SHIPPED scripts/genksyms/lex.lex.c
  SHIPPED scripts/genksyms/keywords.hash.c
  SHIPPED scripts/genksyms/parse.tab.h
  HOSTCC  scripts/genksyms/parse.tab.o
  HOSTCC  scripts/dtc/fstree.o
  HOSTCC  scripts/dtc/data.o
  HOSTCC  scripts/genksyms/lex.lex.o
  HOSTCC  scripts/dtc/livetree.o
  HOSTCC  scripts/dtc/treesource.o
  HOSTCC  scripts/dtc/srcpos.o
  HOSTCC  scripts/dtc/checks.o
  HOSTCC  scripts/dtc/util.o
  SHIPPED scripts/dtc/dtc-lexer.lex.c
  SHIPPED scripts/dtc/dtc-parser.tab.h
  SHIPPED scripts/dtc/dtc-parser.tab.c
  HOSTCC  scripts/dtc/dtc-lexer.lex.o
  HOSTCC  scripts/dtc/dtc-parser.tab.o
  HOSTLD  scripts/genksyms/genksyms
  HOSTLD  scripts/dtc/dtc
Makefile:573: recipe for target 'scripts' failed
make: *** [scripts] Error 2

**Comment by ChBirender** [comment]
Dear Mr. @hizukiayaka ,

Thank you for your support.

I have compiled the kernel.

Will test it and update here.

Regards.

**Comment by hizukiayaka** [comment]
Hi, man, I have a penis as well.

**Comment by ChBirender** [comment]
Dear All,

Raised new issue 
https://github.com/ayufan-rock64/android-7.1/issues/16

Tested kernel build using
make ARCH=arm64 rockchip_defconfig
make -j8 ARCH=arm64 rk3328-rock64.img
It goes to infinite boot loop.

I have replaced
https://github.com/rockchip-linux/kernel
source with
https://github.com/ayufan-rock64/android-kernel
As used in steps
https://forum.pine64.org/showthread.php?tid=5036

Now Meting boot loop.
Please check both logs

1. Error with 4.4 kernel.
2. Normal working with 3.10.104

[Error.txt](https://github.com/rockchip-linux/kernel/files/1649505/Error.txt)
[normaldbg.txt](https://github.com/rockchip-linux/kernel/files/1649506/normaldbg.txt)


Mr. @hizukiayaka , Its for you.
Its seems to be SDMMC not supported,
as image flashed on Micro SD card.
[    2.005855] init: SDMMC OR EMMC ?s1=(null)
[    2.005982] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=0
[    2.006052] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=1
[    2.006122] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=2
[    2.006195] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=3
[    2.006265] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=4
[    2.006334] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=5
[    2.006420] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=6
[    2.006489] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=7
[    2.006559] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=8
[    2.006632] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=9
[    2.006702] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=10
[    2.006772] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=11
[    2.006843] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=12
[    2.006913] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=13
[    2.006983] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=14
[    2.007053] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=15
[    2.007123] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=16
[    2.007193] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=17
[    2.007264] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=18
[    2.007335] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=19

Regards.

**Comment by SinghBirender** [comment]
I have replaced
https://github.com/rockchip-linux/kernel
source with
https://github.com/ayufan-rock64/android-kernel
As used in steps
https://forum.pine64.org/showthread.php?tid=5036

Now Meting boot loop.
Please check both logs

1. Error with 4.4 kernel.
2. Normal working with 3.10.104
[Error.txt](https://github.com/rockchip-linux/kernel/files/1649455/Error.txt)
[normaldbg.txt](https://github.com/rockchip-linux/kernel/files/1649456/normaldbg.txt)

**Comment by mcerveny** [comment]
At least this patch ayufan-rock64/linux-kernel@b158cf169fe451f745bab066a5d38e03644b65ba is essential to get ethernet working. ~~Maybe other patches for [RTL8211F](https://github.com/ayufan-rock64/linux-kernel/commits/release-4.4?after=fbcc627e5c200c4df59903e5992f1de3ba5d59ce+78) should be useful.~~

**Comment by ayufan** [comment]
@mcerveny they are not needed

**Comment by mcerveny** [comment]
@ayufan my ethernet is not stable (after few packets hungs) without ayufan-rock64/linux-kernel@b158cf169fe451f745bab066a5d38e03644b65ba or do you mean RTL8211F series ?

**Comment by ayufan** [comment]
We need only https://github.com/ayufan-rock64/linux-kernel/commit/b158cf169fe451f745bab066a5d38e03644b65ba. The RTL8211F series is not needed.

**Comment by ChBirender** [comment]
Same state
[Error2.txt](https://github.com/rockchip-linux/kernel/files/1665404/Error2.txt)

[rk3328-rock64.dts.tar.gz](https://github.com/rockchip-linux/kernel/files/1665412/rk3328-rock64.dts.tar.gz)
&gmac2io {
	phy-supply = <&vcc_io>;
	phy-mode = "rgmii";
	assigned-clocks = <&cru SCLK_MAC2IO>, <&cru SCLK_MAC2IO_EXT>;
	assigned-clock-parents = <&gmac_clkin>, <&gmac_clkin>;
	clock_in_out = "input";
	snps,reset-gpio = <&gpio1 18 GPIO_ACTIVE_LOW>;
	snps,reset-active-low;
	snps,reset-delays-us = <0 10000 50000>;
	snps,force_thresh_dma_mode;
	pinctrl-names = "default";
	pinctrl-0 = <&rgmiim1_pins>;
	tx_delay = <0x24>;
	rx_delay = <0x18>;
	status = "okay";
};

**Comment by mcerveny** [comment]
As I wrote this repair is for gmac ethernet for (generic) release-4.4. I am using this release-4.4 from this repository without any problem to boot rock64 from sdcard to debian/stretch/linaro builded with rockchip [build system](https://github.com/rockchip-linux/build) (better to boot over SPI-NOR with patched uboot - https://github.com/ayufan-rock64/linux-build/releases - u-boot-flash-spi.img.xz). It is something bad in your private build system/parameters setup for release-4.4 for android. For example "androidboot.hardware=rk30board" ? I am not able to help you with android build.

**Comment by ChBirender** [comment]
Dear Martin Cerveny(@mcerveny ),

I have simply replaced kernel code as setup by Mr. Kamil Trzciński(@ayufan )
using https://github.com/ayufan-rock64/android-7.1/releases

I´m also looking for standard code provided by https://github.com/rockchip-linux/kernel
for rock64.
But for android system, not Linux system.

As per my understanding code setup done by Mr. Kamil Trzciński, is the one internally provided by RockChip Corporation for ROCK64 board.

But we need official code setup provided under
http://opensource.rock-chips.com/wiki_Main_Page project.  

Regards.

**Comment by ChBirender** [comment]
Dear All,

After applying logs in 
"android"/system/core/init/init.cpp

} else {
    for (int i = 0; i < EMMC_RETRY_COUNT_SD; i++) {
		proc_read( "/proc/cmdline", cmdline, sizeof(cmdline) );
		NOTICE("cmdline=%s\n",cmdline);
		s1 = strstr(cmdline, STORAGE_MEDIA_SD);
		s2 = strstr(cmdline, "androidboot.mode=sd");
		s3 = strstr(cmdline, " androidboot.hardware=rkd");
		ERROR("s1=%s\n",s1);
		ERROR("s2=%s\n",s2);
		ERROR("s3=%s\n",s3);
		if ((s1 > 0) && (s2 > 0)) {
			ERROR("OK,SDMMC DRIVERS INIT OK\n");
			property_set("ro.boot.mode", "sd");
			break;
		} else {
			ERROR("ERROR,SDMMC DRIVERS NOT READY, RERRY=%d\n", i);
		}
	}
}

Working:
https://github.com/ayufan-rock64/linux-kernel
[    4.175317]  [0:           init:    1] init: init first stage started!
[    4.230871]  [0:           init:    1] type=1403 audit(1.710:2): policy loaded auid=4294967295 ses=4294967295
[    4.231410]  [0:           init:    1] init: (Initializing SELinux non-enforcing took 0.06s.)
[    4.234403]  [0:           init:    1] init: init second stage started!
[    4.234484]  [0:           init:    1] init: init: 1111
[    4.237798]  [0:           init:    1] init: init: 2222
[    4.237994]  [0:           init:    1] init: init: 3333
[    4.238271]  [0:           init:    1] init: init: 4444
[    4.238334]  [0:           init:    1] init: SDMMC OR EMMC ?s1=(null)
[    4.238385]  [0:           init:    1] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rkd
[    4.238385]  [0:           init:    1] 
[    4.238445]  [0:           init:    1] init: s1=storagemedia=sd uboot_logo=0x02000000@0x3dc00000:0x01000000 loader.timestamp=2017-10-06_09:09:16 hdmi.vic=16 tve.format=-1 SecureBootCheckOk=0 androidbod
[    4.238445]  [0:           init:    1] 
[    4.238474]  [0:           init:    1] init: s2=androidboot.mode=sd
[    4.238474]  [0:           init:    1] 
[    4.238500]  [0:           init:    1] init: s3=(null)
[    4.238517]  [0:           init:    1] init: OK,SDMMC DRIVERS INIT OK
[    4.238544]  [0:           init:    1] init: property_set("ro.boot.mode", "sd") failed
[    4.238614]  [0:           init:    1] init: property_set("ro.hardware", "rk30board") failed
[    4.238687]  [0:           init:    1] init: init: 5555
[    4.238816]  [0:           init:    1] init: -----set_soc_if_need,get soc=rk3328,len = 6
[    4.238837]  [0:           init:    1] init: ---ready to set ro.rk.soc to rk3328
[    4.238864]  [0:           init:    1] init: init: 6666
[    4.247544]  [0:           init:    1] init: Running restorecon...

Error:
https://github.com/rockchip-linux/kernel
[    1.934507] init: init first stage started!
[    1.995553] audit: type=1403 audit(1.990:2): policy loaded auid=4294967295 ses=4294967295
[    1.996389] init: (Initializing SELinux non-enforcing took 0.06s.)
[    2.000382] init: init second stage started!
[    2.000515] init: init: 1111
[    2.004918] init: init: 2222
[    2.005220] init: init: 3333
[    2.005550] init: init: 4444
[    2.005651] init: SDMMC OR EMMC ?s1=(null)
[    2.005701] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.005701] 
[    2.005744] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.005744] 
[    2.005757] init: s2=(null)
[    2.005767] init: s3=(null)
[    2.005779] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=0
[    2.005827] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.005827] 
[    2.005869] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.005869] 
[    2.005882] init: s2=(null)
[    2.005891] init: s3=(null)
[    2.005903] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=1
[    2.005949] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.005949] 
[    2.005991] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.005991] 
[    2.006003] init: s2=(null)
[    2.006013] init: s3=(null)
[    2.006025] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=2
[    2.006072] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.006072] 
[    2.006132] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.006132] 
[    2.006147] init: s2=(null)
[    2.006156] init: s3=(null)
[    2.006169] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=3
[    2.006216] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.006216] 
[    2.006258] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.006258] 
[    2.006272] init: s2=(null)
[    2.006281] init: s3=(null)
[    2.006295] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=4
[    2.006343] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.006343] 
[    2.006384] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.006384] 
[    2.006397] init: s2=(null)
[    2.006407] init: s3=(null)
[    2.006419] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=5
[    2.006473] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.006473] 
[    2.006514] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.006514] 
[    2.006527] init: s2=(null)
[    2.006536] init: s3=(null)
[    2.006549] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=6
[    2.006596] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.006596] 
[    2.006638] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.006638] 
[    2.006651] init: s2=(null)
[    2.006660] init: s3=(null)
[    2.006673] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=7
[    2.006719] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.006719] 
[    2.006760] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.006760] 
[    2.006773] init: s2=(null)
[    2.006782] init: s3=(null)
[    2.006794] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=8
[    2.006841] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.006841] 
[    2.006884] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.006884] 
[    2.006898] init: s2=(null)
[    2.006907] init: s3=(null)
[    2.006919] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=9
[    2.006967] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.006967] 
[    2.007008] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.007008] 
[    2.007021] init: s2=(null)
[    2.007030] init: s3=(null)
[    2.007044] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=10
[    2.007091] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.007091] 
[    2.007133] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.007133] 
[    2.007145] init: s2=(null)
[    2.007155] init: s3=(null)
[    2.007167] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=11
[    2.007216] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.007216] 
[    2.007257] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.007257] 
[    2.007270] init: s2=(null)
[    2.007279] init: s3=(null)
[    2.007291] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=12
[    2.007339] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.007339] 
[    2.007439] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.007439] 
[    2.007453] init: s2=(null)
[    2.007463] init: s3=(null)
[    2.007476] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=13
[    2.007528] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.007528] 
[    2.007569] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.007569] 
[    2.007582] init: s2=(null)
[    2.007591] init: s3=(null)
[    2.007605] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=14
[    2.007652] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.007652] 
[    2.007693] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.007693] 
[    2.007706] init: s2=(null)
[    2.007716] init: s3=(null)
[    2.007730] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=15
[    2.007777] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.007777] 
[    2.007818] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.007818] 
[    2.007831] init: s2=(null)
[    2.007841] init: s3=(null)
[    2.007853] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=16
[    2.007900] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.007900] 
[    2.007941] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.007941] 
[    2.007955] init: s2=(null)
[    2.007964] init: s3=(null)
[    2.007977] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=17
[    2.008053] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.008053] 
[    2.008094] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.008094] 
[    2.008108] init: s2=(null)
[    2.008117] init: s3=(null)
[    2.008130] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=18
[    2.008178] init: cmdline=rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 console=ttyFIQ0 androidboot.baseband=N/A androidboot.selinux=permissive androidboot.hardware=rk30board androidboot.console0
[    2.008178] 
[    2.008219] init: s1=storagemedia=sd loader.timestamp=2017-10-06_09:09:16 hdmi.vic=-1 tve.format=-1 SecureBootCheckOk=0
[    2.008219] 
[    2.008232] init: s2=(null)
[    2.008241] init: s3=(null)
[    2.008254] init: ERROR,SDMMC DRIVERS NOT READY, RERRY=19
[    2.008354] init: property_set("ro.hardware", "rk30board") failed
[    2.008490] init: init: 5555
[    2.008640] init: init: 6666
[    2.011215] init: Running restorecon...

Cause:
proc_read( "/proc/cmdline", cmdline, sizeof(cmdline) );
not having androidboot.mode=sd

**Comment by ChBirender** [comment]
Dear Zhangbin Tong.

I will test :
https://github.com/rockchip-linux/kernel/commit/c170469b8ba86e29e586d8e814904984edf82d8b
And will update here.

Regards.

**Comment by ChBirender** [comment]
Dear All,

It is having SD-MMC issue as mentioned above.

Regards.
