### ISSUE TITLE
Does rk3399 linux kernel support dual mipi port for ovXXX camera?

### ISSUE THREAD

**Issue by gangm** [rockchip-linux/kernel#47]
hi,
we want to use ov13850 camera in ubuntu system based on firefly rk3399, but seems like that the firefly ubuntu system does not support dual mipi port driver...
Is there any plan to support ubuntu(linux) dual mipi camera in the future? thanks!~

**Comment by wzyy2** [comment]
What do you mean `dual mipi`?
Please see https://github.com/rockchip-linux/kernel/issues/33 and sorry i can't guarantee you when it will be support, maybe you could help us do it(refer to old rk-isp10 driver). 
:-)
