### ISSUE TITLE
Fireprime RK3128 doesn’t boot

### ISSUE THREAD

**Issue by harsszegi** [rockchip-linux/kernel#53]
Hello,

compiled system.img for Fireprime RK3128, but not even uboot starts (Minicom shows nothing)
Please advise. Thanks,

**Comment by FallingSnow** [comment]
If uboot doesn't even show you have a problem with uboot, not the kernel. Have you been able to use the serial console before?

**Comment by harsszegi** [comment]
Hell yes, stock fireprime works fine with minicom.
I understand that it most probably not the kernel,
just that I have zero idea where to report generic - most probably - build/mk-* + rkbin/ related stuff

**Comment by FallingSnow** [comment]
https://github.com/rockchip-linux/u-boot
