### ISSUE TITLE
rk3288 tinker board no videoX device

### ISSUE THREAD

**Issue by zillevdr** [rockchip-linux/kernel#6]
Hello,

with branch release-4.4 configured with rockchip_linux_defconfig I get no /dev/videoX device. With kernel from TinderOS is there video0 and video1.
This is dmesg:

[dmesg.txt](https://github.com/rockchip-linux/kernel/files/853268/dmesg.txt)

Regards zillevdr

**Comment by wzyy2** [comment]
They are replaced with /dev/vpu_service and /dev/hevc_service.
