### ISSUE TITLE
Kernel 4.4.114 DRM stopped after the first frame

### ISSUE THREAD

**Issue by zillevdr** [rockchip-linux/kernel#71]
Last weckend i had updated the kernel from 4.4.103 to 4.4.114. When I play video DRM stopped after the first frame is on the screen. The config is rockchip_linux_defconfig. With kernel 4.4.103-rockchip it work fine.

dmesg with 4.4.103-rockchip:
[   47.354088] [drm:hdmi_config_hdr_infoframe] *ERROR* Not support DRM Infoframe

dmesg with 4.4.114-rockchip:
[  161.600251] rockchip-vop ff930000.vop: [drm:vop_crtc_enable] Update mode to 1920*1080, close all win
[  161.622797] [drm:hdmi_config_hdr_infoframe] *ERROR* Not support DRM Infoframe
[  179.940407] rockchip-vop ff930000.vop: wait win close timeout

Best regards
zille

**Comment by wzyy2** [comment]
which userspace do you use to play video? gstreamer?

**Comment by zillevdr** [comment]
No, I have written an plugin for vdr: https://github.com/zillevdr/vdr-plugin-softhddevice/tree/drm
With kernel 4.4.103-rockchip run perfect, with kernel 4.4.114-rockchip it stops after the first frame is on screen.

**Comment by zillevdr** [comment]
The issue was on the audio path here. Sorry for trouble.
Best regards zille
