### ISSUE TITLE
CRLF/CR

### ISSUE THREAD

**Issue by mcerveny** [rockchip-linux/kernel#9]
Hello.

Most of Rockchip source code are using randomly CRLF, mixed LF and CRLF and even CR-only line separators. Can you review your source code and place LF-only line separators ?

Thanks.

[with_at_least_one_cr.txt](https://github.com/rockchip-linux/kernel/files/914627/with_at_least_one_cr.txt)

**Comment by wzyy2** [comment]
umm... It's hard to correct it since most rockchip engineer use win....

close it.

**Comment by mcerveny** [comment]
Windows is not problem search for git "core.autocrlf" configuration or use appropriate text editor.
